[phases.setup]
nixPkgs = ["php", "php-fpm", "python311Packages.supervisor"]  # Added explicit PHP-FPM

[phases.build]
cmds = [
    "mkdir -p /etc/supervisor/conf.d/",
    "cp /assets/worker-*.conf /etc/supervisor/conf.d/",
    "cp /assets/supervisord.conf /etc/supervisord.conf",
    "chmod +x /assets/start.sh",
    "chmod -R 775 /app/storage /app/bootstrap/cache",
    "chown -R www-data:www-data /app",
    "chmod -R a+rwx /app/storage/logs",
    "touch /app/storage/logs/laravel.log",
    "chown www-data:www-data /app/storage/logs/laravel.log",
    "chmod 664 /app/storage/logs/laravel.log",
    "touch /app/database/database.sqlite",
    "chown www-data:www-data /app/database/database.sqlite",
    "chmod 664 /app/database/database.sqlite",
    "[[ -n \"$FIREBASE_CONFIG\" ]] && echo $FIREBASE_CONFIG | base64 -d > /app/storage/app/firebase_credentials.json || echo 'FIREBASE_CONFIG not set'",
    "..."
]

[start]
cmd = "/assets/start.sh"

[staticAssets]
"start.sh" = '''
#!/bin/bash

# Transform the nginx configuration
node /assets/scripts/prestart.mjs /assets/nginx.template.conf /etc/nginx.conf

# Wait for PHP-FPM to be ready (NEW CRITICAL LINE)
while ! nc -z 127.0.0.1 9000; do sleep 1; done

# Clear cache
su -s /bin/bash -c "php /app/artisan config:cache" www-data
su -s /bin/bash -c "php /app/artisan route:cache" www-data
su -s /bin/bash -c "php /app/artisan view:cache" www-data

# Start supervisor
supervisord -c /etc/supervisord.conf -n
'''

"worker-phpfpm.conf" = '''
[program:worker-phpfpm]
process_name=%(program_name)s_%(process_num)02d
command=php-fpm --nodaemonize --fpm-config /assets/php-fpm.conf  # Changed command format
autostart=true
autorestart=true
startretries=5
stdout_logfile=/var/log/worker-phpfpm.log
stderr_logfile=/var/log/worker-phpfpm.log
'''

"php-fpm.conf" = '''
[www]
listen = 127.0.0.1:9000
user = www-data
group = www-data
listen.owner = www-data
listen.group = www-data
pm = dynamic
pm.max_children = 50
pm.min_spare_servers = 4
pm.max_spare_servers = 32
pm.start_servers = 18
clear_env = no

# Environment variables
env[APP_ENV] = production
env[HTTPS] = on
env[HTTP_X_FORWARDED_PROTO] = https

# Error logging
catch_workers_output = yes
php_flag[display_errors] = on
php_admin_value[error_log] = /var/log/php-fpm-error.log
php_admin_flag[log_errors] = on
'''

"nginx.template.conf" = '''
# Previous config remains the same, just modify the PHP handler:
location ~ \.php$ {
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    
    # Timeout settings
    fastcgi_read_timeout 300;
    
    # HTTPS enforcement
    fastcgi_param HTTPS $http_x_forwarded_proto;
    fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
    
    # Buffer settings
    fastcgi_buffers 16 16k;
    fastcgi_buffer_size 32k;
}
'''